version: '2'

services:
  registry-server:
    image: registry:latest

    ports:
      - 5000:5000
    volumes:
      - ./regdata:/var/lib/registry
      - ./auth:/auth
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
